const assert=require('node:assert/strict');
const {chromium}=require('playwright');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8084');
 await page.getByRole('button',{name:'МАКСМАРКЕТ',exact:true}).click();await page.locator('#company').waitFor({state:'visible'});
 const verdict=await page.locator('#card .v').textContent();
 await page.getByRole('button',{name:'Даю отсрочку',exact:true}).click();
 assert.equal(await page.locator('#card .v').textContent(),verdict);
 assert.match(await page.locator('#card .facts li').first().textContent(),/арбитраж/);
 await page.getByRole('button',{name:'Плачу по счёту',exact:true}).click();
 assert.equal(await page.locator('#card .v').textContent(),verdict);
 let resolveRequest,received;
 const gate=new Promise(r=>resolveRequest=r);
 await page.route('**/v1/runs/stream',async route=>{received=route.request().postDataJSON();await gate;await route.fulfill({status:200,contentType:'text/event-stream',body:'data: '+JSON.stringify({type:'end',data:{output:{kind:'answer',text_md:'В отчёте нет сведений о сотрудниках.\n\nОтчёт от 31.07.2026.',report_dates:{'5032257375':'2026-07-31'},citations:[{claim:'Сотрудники не указаны',inn:'5032257375',source_path:'report.baseInfo.staff'}]}}})+'\n\n'});});
 const input=page.locator('#ask');await input.fill('Сколько сотрудников?');await input.press('Shift+Enter');assert.equal(await input.inputValue(),'Сколько сотрудников?\n');
 await input.press('Enter');await page.waitForFunction(()=>document.querySelector('#askbtn').disabled);
 await input.fill('Следующий вопрос');await input.press('Enter');assert.equal(await input.inputValue(),'Следующий вопрос');
 resolveRequest();await page.waitForFunction(()=>!document.querySelector('#askbtn').disabled);
 assert.equal(await input.inputValue(),'Следующий вопрос');assert.match(received.input.messages[0].content,/5032257375/);
 assert.equal(await page.locator('#thread .turn.user').count(),1);
 assert.equal(await page.locator('#thread .status:visible').count(),0);
 assert.equal(await page.locator('#card .verdict').count(),1);
 assert.equal(await page.locator('#thread .actions').count(),1);
 assert.ok(await page.evaluate(()=>{const e=document.querySelector('#workspace');return e.scrollHeight-e.clientHeight-e.scrollTop<180;}));
 await page.reload();await page.locator('#thread .answer .body').waitFor({state:'visible'});
 assert.match(await page.locator('#thread').textContent(),/Сколько сотрудников/);
 await page.locator('#thread').getByRole('button',{name:'Показать основания · 1'}).click();await page.locator('[data-source="0"] summary').click();await page.locator('.source-data pre').first().waitFor();assert.match(await page.locator('.source-data').textContent(),/не указано/);await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Сравнить компании',exact:true}).click();await page.getByRole('button',{name:'ГДК, ТЕХПРОФ и БИЛД-ЮГ',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('#cmpgo').disabled && document.querySelectorAll('#selected .chip').length===3);await page.locator('#cmpgo').click();assert.equal(await page.locator('.group').count(),3);assert.match(await page.locator('.group.ok').textContent(),/ТЕХПРОФ/);assert.equal(await page.locator('#cmpBody [data-report]').count(),3);
 await page.locator('#cmpSources').click();assert.ok(await page.locator('[data-source]').count()>3);await page.keyboard.press('Escape');
 await page.locator('#cmpBody [data-report]').first().click();await page.locator('#reportSources').waitFor();await page.locator('#reportSources').click();assert.ok(await page.locator('[data-source]').count()>2);await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Для агентов банка',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#mcphead').textContent==='8 функций');assert.ok(!(await page.locator('#mcpjson').textContent()).includes('/Users/'));
 await page.getByRole('button',{name:'Качество ответов',exact:true}).click();await page.locator('#qtable th').first().waitFor();assert.equal(await page.locator('#qtable thead th').count(),4);
 await page.getByRole('button',{name:'＋ Новая проверка',exact:true}).click();await page.getByRole('button',{name:'ТЕХПРОФ',exact:true}).click();await page.locator('#company').waitFor({state:'visible'});
 assert.ok(!(await page.locator('#card').textContent()).includes('штате напрямую'));
 await page.screenshot({path:'/tmp/contractor-develop-desktop.png'});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/contractor-develop-mobile.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.equal(errors.length,0,errors.join('\n'));
 console.log('PASS: Enter/Shift+Enter, draft during generation, automatic scroll, reload/history, evidence, goal ordering, unchanged verdict, comparison groups, MCP, quality, mobile overflow, no JS errors.');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
